### PR TITLE
complete: enable complete.Complete() output capturing

### LINKED ISSUE #137: complete: the output of complete.Complete() cannot be captured
## Repro

<details><summary>Test the <code>gocomplete</code> package. The <code>Example</code> test fails.</summary>

```shell
$ go test ./gocomplete/
run
--- FAIL: Example (0.00s)
got:

want:
run
FAIL
FAIL    github.com/posener/complete/v2/gocomplete       0.004s
FAIL
```
</details>

<details><summary>Implementing an analogous test in the <code>complete</code> package confirms this as a problem in the latter.</summary>

```diff
diff --git a/complete_test.go b/complete_test.go
index 3a0809f..e26522e 100644
--- a/complete_test.go
+++ b/complete_test.go
@@ -3,6 +3,7 @@ package complete
 import (
 	"io/ioutil"
 	"os"
+	"strconv"
 	"testing"
 
 	"github.com/posener/complete/v2/internal/arg"
@@ -214,6 +215,42 @@ func TestComplete(t *testing.T) {
 	}
 }
 
+// ExampleComplete_outputCapturing demonstrates the ability to capture
+// the output of Complete() invocations, crucial for integration tests.
+func ExampleComplete_outputCapturing() {
+	// a stringLookup function maps one string to another.
+	// os.GetEnv is an instance of such a function.
+	type stringLookup = func(string) string
+
+	// promptEnv returns stringLookup func that emulates the environment
+	// variables a shell would set when its prompt has the given contents.
+	var promptEnv = func(contents string) stringLookup {
+		return func(key string) string {
+			switch key {
+			case "COMP_LINE":
+				return contents
+			case "COMP_POINT":
+				return strconv.Itoa(len(contents))
+			}
+			return ""
+		}
+	}
+
+	defer func(f func(int)) { exit = f }(exit)
+	defer func(f stringLookup) { getEnv = f }(getEnv)
+	exit = func(int) {}
+
+	// This is where the actual example starts:
+
+	cmd := &Command{Sub: map[string]*Command{"bar": {}}}
+	getEnv = promptEnv("foo b")
+
+	Complete("foo", cmd)
+
+	// Output:
+	// bar
+}
+
 type set []string
 
 func (s set) Predict(_ string) []string {
```

```shell
$ go test -run=^Example -v
=== RUN   ExampleComplete_outputCapturing
bar
--- FAIL: ExampleComplete_outputCapturing (0.00s)
got:

want:
bar
FAIL
FAIL    github.com/posener/complete/v2  0.003s
FAIL
```
</details>

## Expectation `^` reality

That's an easy one: everyone would like their tests to never fail, but these ones do. :disappointed: 

## Cause

The root cause lies in the line 54 here:

https://github.com/posener/complete/blob/002575c9d5d6c6e162302512c5b899920e839e56/complete.go#L52-L56

It defines a global `var out io.Writer`, assigned to at the [package initialization][init] ([this article][yb] seems a bit more explicit on the sequence).

This means that by the time tests (in this case, [`testing.runExample()`][runExample], to be precise) finally get around to capturing `stdout`, it has already been effectively hard-coded to the initial value throughout the `complete` package. Which in turn means that nothing outside of `complete` can ever change where the output goes to, therefore no tests in the world (apart from the `complete` package itself) can ever see what's really going on with the output.

[init]: https://golang.org/doc/effective_go#initialization
    (Initialization - Effective Go - The Go Programming Language)
[yb]: https://yourbasic.org/golang/package-init-function-main-execution-order/
    (Package initialization and program execution order · YourBasic Go)
[runExample]: https://github.com/golang/go/blob/go1.16/src/testing/run_example.go#L21-L66
    (go/run_example.go at go1.16 · golang/go)

### PR DESCRIPTION
**Pull request by antichris**
By moving the input/output stream variable initializations into `complete.Complete()` it always uses the `os.Stdout` stream as it is at the moment of invocation and we ensure that its callers have an opportunity to assert control over where the output goes to. This resolves #137.

<details><summary>Now the tests actually do pass.</summary>

```shell
$ go test -run=^Example -v . ./gocomplete/
=== RUN   ExampleComplete_outputCapturing
--- PASS: ExampleComplete_outputCapturing (0.00s)
PASS
ok      github.com/posener/complete/v2  0.003s
=== RUN   Example
--- PASS: Example (0.00s)
PASS
ok      github.com/posener/complete/v2/gocomplete       0.004s
```
</details>

<details><summary>And they really do expose failures — or unexpected output at the very least.</summary>

```diff
diff --git a/complete_test.go b/complete_test.go
index 182ca4c..8744b56 100644
--- a/complete_test.go
+++ b/complete_test.go
@@ -256,7 +256,7 @@ func ExampleComplete_outputCapturing() {
 	Complete("foo", cmd)
 
 	// Output:
-	// bar
+	// qux
 }
 
 type set []string
diff --git a/gocomplete/tests_test.go b/gocomplete/tests_test.go
index a1238a4..c7436c8 100644
--- a/gocomplete/tests_test.go
+++ b/gocomplete/tests_test.go
@@ -48,7 +48,7 @@ func Example() {
 	os.Setenv("COMP_LINE", "go ru")
 	os.Setenv("COMP_POINT", "5")
 	main()
-	// output: run
+	// output: duck
 }
 
 func equal(s1, s2 []string) bool {
```

```shell
$ go test -run=^Example -v . ./gocomplete/
=== RUN   ExampleComplete_outputCapturing
--- FAIL: ExampleComplete_outputCapturing (0.00s)
got:
bar
want:
qux
FAIL
FAIL    github.com/posener/complete/v2  0.003s
=== RUN   Example
--- FAIL: Example (0.00s)
got:
run
want:
duck
FAIL
FAIL    github.com/posener/complete/v2/gocomplete       0.003s
FAIL
```
</details>

One lesson that should be learned from this is that actually asserting on the expected output in the `complete` tests would have exposed this much sooner.

### CODE REVIEW

**Comment by antichris** [comment]
Come to think of that, even though this setup sucks less than the previous one, it still kind of sucks.

<details><summary>A more robust design would rely on <em>explicit</em> injection of the I/O streams.</summary>

```diff
diff --git a/complete.go b/complete.go
index 0641c39..8b6d25d 100644
--- a/complete.go
+++ b/complete.go
@@ -56,7 +56,7 @@ var (
 // Complete the command line arguments for the given command in the case that the program
 // was invoked with COMP_LINE and COMP_POINT environment variables. In that case it will also
 // `os.Exit()`. The program name should be provided for installation purposes.
-func Complete(name string, cmd Completer) {
+func Complete(in io.Reader, out io.Writer, name string, cmd Completer) {
 	var (
 		line        = getEnv("COMP_LINE")
 		point       = getEnv("COMP_POINT")
@@ -64,10 +64,6 @@ func Complete(name string, cmd Completer) {
 		doUninstall = getEnv("COMP_UNINSTALL") == "1"
 		yes         = getEnv("COMP_YES") == "1"
 	)
-	var (
-		out io.Writer = os.Stdout
-		in  io.Reader = os.Stdin
-	)
 	if doInstall || doUninstall {
 		install.Run(name, doUninstall, yes, out, in)
 		exit(0)
```
</details>

<details><summary>Not only that would impart the control over the streams to the caller, it would also simplify testing.</summary>

```diff
diff --git a/complete_test.go b/complete_test.go
index 182ca4c..71c802f 100644
--- a/complete_test.go
+++ b/complete_test.go
@@ -1,7 +1,7 @@
 package complete
 
 import (
-	"io"
+	"bytes"
 	"io/ioutil"
 	"os"
 	"strconv"
@@ -163,14 +163,8 @@ func TestComplete(t *testing.T) {
 		exit = os.Exit
 	}()
 
-	in, out, err := os.Pipe()
-	if err != nil {
-		t.Fatal(err)
-	}
-	defer func(o *os.File) { os.Stdout = o }(os.Stdout)
-	defer out.Close()
-	os.Stdout = out
-	go io.Copy(ioutil.Discard, in)
+	in := &bytes.Reader{}
+	out := ioutil.Discard
 
 	tests := []struct {
 		line, point string
@@ -214,9 +208,9 @@ func TestComplete(t *testing.T) {
 				isExit = true
 			}
 			if tt.shouldPanic {
-				assert.Panics(t, func() { testCmd.Complete("") })
+				assert.Panics(t, func() { testCmd.Complete(in, out, "") })
 			} else {
-				testCmd.Complete("")
+				testCmd.Complete(in, out, "")
 				assert.Equal(t, tt.shouldExit, isExit)
 			}
 		})
@@ -253,7 +247,7 @@ func ExampleComplete_outputCapturing() {
 	cmd := &Command{Sub: map[string]*Command{"bar": {}}}
 	getEnv = promptEnv("foo b")
 
-	Complete("foo", cmd)
+	Complete(os.Stdin, os.Stdout, "foo", cmd)
 
 	// Output:
 	// bar
```
</details>

<details><summary>A drawback of this call-site injection approach is that now the callers are responsible for supplying the streams, which could make the invocations feel somewhat cluttered.</summary>

```diff
diff --git a/command.go b/command.go
index 74ab299..e1e4ea0 100644
--- a/command.go
+++ b/command.go
@@ -1,5 +1,7 @@
 package complete
 
+import "io"
+
 // Command is an object that can be used to create complete options for a go executable that does
 // not have a good binding to the `Completer` interface, or to use a Go program as complete binary
 // for another executable (see ./gocomplete as an example.)
@@ -16,8 +18,8 @@ type Command struct {
 }
 
 // Complete runs the completion of the described command.
-func (c *Command) Complete(name string) {
-	Complete(name, c)
+func (c *Command) Complete(in io.Reader, out io.Writer, name string) {
+	Complete(in, out, name, c)
 }
 
 func (c *Command) SubCmdList() []string {
diff --git a/compflag/compflag.go b/compflag/compflag.go
index 2048c74..443cada 100644
--- a/compflag/compflag.go
+++ b/compflag/compflag.go
@@ -36,6 +36,7 @@ package compflag
 
 import (
 	"flag"
+	"io"
 	"os"
 	"strconv"
 	"time"
@@ -63,15 +64,15 @@ func (fs *FlagSet) Lookup(name string) *flag.Flag { return (*flag.FlagSet)(fs).L
 func (fs *FlagSet) Parsed() bool                  { return (*flag.FlagSet)(fs).Parsed() }
 
 // Complete performs bash completion if needed.
-func (fs *FlagSet) Complete() {
-	complete.Complete(fs.Name(), complete.FlagSet((*flag.FlagSet)(CommandLine)))
+func (fs *FlagSet) Complete(in io.Reader, out io.Writer) {
+	complete.Complete(in, out, fs.Name(), complete.FlagSet((*flag.FlagSet)(CommandLine)))
 }
 
 var CommandLine = (*FlagSet)(flag.CommandLine)
 
 // Parse parses command line arguments. It also performs bash completion when needed.
-func Parse() {
-	CommandLine.Complete()
+func Parse(in io.Reader, out io.Writer) {
+	CommandLine.Complete(in, out)
 	CommandLine.Parse(os.Args[1:])
 }
 
diff --git a/example/command/main.go b/example/command/main.go
index c8c1414..7681671 100644
--- a/example/command/main.go
+++ b/example/command/main.go
@@ -30,7 +30,7 @@ func main() {
 	}
 
 	// Run the completion.
-	cmd.Complete("command")
+	cmd.Complete(os.Stdin, os.Stdout, "command")
 
 	// Parse the flags.
 	flag.Parse()
diff --git a/example/compflag/main.go b/example/compflag/main.go
index 1d51307..2cb63cb 100644
--- a/example/compflag/main.go
+++ b/example/compflag/main.go
@@ -20,7 +20,7 @@ var (
 
 func main() {
 	// Parse flags and perform bash completion if needed.
-	compflag.Parse()
+	compflag.Parse(os.Stdin, os.Stdout)
 
 	// Program logic.
 	if *name == "" {
diff --git a/example/stdlib/main.go b/example/stdlib/main.go
index c54130c..aded633 100644
--- a/example/stdlib/main.go
+++ b/example/stdlib/main.go
@@ -20,7 +20,7 @@ var (
 func main() {
 	// Run the completion. Notice that since we are using standard library flags, only the flag
 	// names will be completed and not their values.
-	complete.CommandLine()
+	complete.CommandLine(os.Stdin, os.Stdout)
 
 	// Parse the flags.
 	flag.Parse()
diff --git a/flags.go b/flags.go
index 3a1cdfd..f3d30a7 100644
--- a/flags.go
+++ b/flags.go
@@ -2,11 +2,12 @@ package complete
 
 import (
 	"flag"
+	"io"
 )
 
 // Complete default command line flag set defined by the standard library.
-func CommandLine() {
-	Complete(flag.CommandLine.Name(), FlagSet(flag.CommandLine))
+func CommandLine(in io.Reader, out io.Writer) {
+	Complete(in, out, flag.CommandLine.Name(), FlagSet(flag.CommandLine))
 }
 
 // FlagSet returns a completer for a given standard library `flag.FlagSet`. It completes flag names,
diff --git a/gocomplete/complete.go b/gocomplete/complete.go
index 753a38e..e552b92 100644
--- a/gocomplete/complete.go
+++ b/gocomplete/complete.go
@@ -2,6 +2,8 @@
 package main
 
 import (
+	"os"
+
 	"github.com/posener/complete/v2"
 	"github.com/posener/complete/v2/predict"
 )
@@ -633,5 +635,5 @@ func main() {
 		},
 	}
 
-	gogo.Complete("go")
+	gogo.Complete(os.Stdin, os.Stdout, "go")
 }
```
</details>

The most ergonomic API I can think of right now would probably be similar e.g. Go stdlib `log.Writer`, with a globally available package-default service instance using the standard I/O streams by default. But ISTM implementing that effectively would require yet another extensive redesign, likely to significantly increase the complexity with no practical benefit: most applications, after all, would only ever need `Complete` to execute just once per a run using the standard streams.

File: complete_test.go [hunk 1]
```diff
@@ -214,6 +223,42 @@ func TestComplete(t *testing.T) {
...
+				return contents
+			case "COMP_POINT":
+				return strconv.Itoa(len(contents))
+			}
+			return ""
+		}
+	}
+
+	defer func(f func(int)) { exit = f }(exit)
+	defer func(f stringLookup) { getEnv = f }(getEnv)
```
Comment (posener) [inline complete_test.go:248]: Maybe it would be a bit clearer just to copy the values into a local variable and just invoke a single defer function that restores them?

Also, I think it would make things easier to read if `exit` and `getEnv` one after the other.

File: complete_test.go [hunk 2]
```diff
@@ -214,6 +223,42 @@ func TestComplete(t *testing.T) {
 	}
 }
 
+// ExampleComplete_outputCapturing demonstrates the ability to capture
+// the output of Complete() invocations, crucial for integration tests.
+func ExampleComplete_outputCapturing() {
+	// a stringLookup function maps one string to another.
```
Comment (posener) [inline complete_test.go:229]: Maybe for the sake of making the example easier to read, define them outside the function?

File: complete_test.go [hunk 3]
```diff
@@ -214,6 +223,42 @@ func TestComplete(t *testing.T) {
...
+	// os.GetEnv is an instance of such a function.
+	type stringLookup = func(string) string
```
Comment (posener) [inline complete_test.go:231]: nit: I would rename to `getEnvFn` to make things more explicit.

**Review by posener — COMMENTED** [review]
Nice!
Good catch!

Few cosmetic comments...

File: complete_test.go (hunk 1 above)
Comment (antichris) [reply complete_test.go:248]: On one hand, I agree.

On the other... Each of these lines is a completely self-contained instance of that curious Go-specific "deferred self-restoring memento" pattern (I think of them as "time-capsules"). Things can be refactored, renamed, moved around, but each of those closures holds on to the respective original value and will faithfully restore it, once the enclosing scope is done, without littering the latter with variables that could accidentally get in the way of other stuff. Once you get used to this pattern, it reads very naturally and the intention is unambiguously clear — nothing else can happen than a variable getting back its original value as soon as the enclosing function returns.

<details><summary>At one point I considered merging both of those closures in a single one, but that felt markedly clumsier to me.</summary>

```diff
diff --git a/complete_test.go b/complete_test.go
index 182ca4c..e0cf61e 100644
--- a/complete_test.go
+++ b/complete_test.go
@@ -244,8 +244,10 @@ func ExampleComplete_outputCapturing() {
 		}
 	}
 
-	defer func(f func(int)) { exit = f }(exit)
-	defer func(f stringLookup) { getEnv = f }(getEnv)
+	defer func(_exit func(int), _getEnv stringLookup) {
+		exit = _exit
+		getEnv = _getEnv
+	}(exit, getEnv)
 	exit = func(int) {}
 
 	// This is where the actual example starts:
```
</details>

Either way, it's not like I'm surgically attached to those lines, if you have a clear idea of what you'd prefer to see, put it in a comment and I'll implement it precisely that way in the PR.

File: complete_test.go (hunk 2 above)
Comment (antichris) [reply complete_test.go:229]: I did consider it, but then fell back to this, as I didn't think it was worth littering the package scope with symbols that have no other use but this one silly test. But, sure, can do.

File: complete_test.go (hunk 1 above)
Comment (antichris) [reply complete_test.go:248]: <details><summary>Oh, right, I totally forgot about multiple assignment.</summary>

```diff
diff --git a/complete_test.go b/complete_test.go
index 182ca4c..9d82263 100644
--- a/complete_test.go
+++ b/complete_test.go
@@ -244,8 +244,9 @@ func ExampleComplete_outputCapturing() {
 		}
 	}
 
-	defer func(f func(int)) { exit = f }(exit)
-	defer func(f stringLookup) { getEnv = f }(getEnv)
+	defer func(_exit func(int), _getEnv stringLookup) {
+		exit, getEnv = _exit, _getEnv
+	}(exit, getEnv)
 	exit = func(int) {}
 
 	// This is where the actual example starts:
```

I'm still not sold though.
</details>

Was this what you had in mind?

Comment (posener) [reply complete_test.go]: The current implementation is fine.
However, I don't understand why you explicitly need to pass them to the deferred function, and not borrow them from the outer scope:

```
prevExit, prevGetEnv := ...
defer func() {  exit, getEnv = prevExit, prevGetEnv }()
```

File: complete_test.go (hunk 2 above)
Comment (posener) [reply complete_test.go]: Thanks
Looks much cleaner to my eyes :eyes:

File: complete_test.go (hunk 1 above)
Comment (antichris) [reply complete_test.go]: <details><summary>No need, really, just a personal preference.</summary>

1. I don't have to come up with a variable name (or a naming convention) that's semantic yet unique in the enclosing (outer) scope and has no potential for collisions as the code grows and changes with time.
2. There is absolutely zero chance of accidentally messing things up (e.g. overwriting the old value).
3. It makes for a single, clear, concise, perfectly reproducible pattern to follow with no additional thought to be given to, ever again.
4. Refactoring is straightforward, no diff churn — every single `defer` line stands on its own.

So, instead of

```golang
// Would "oldX" be better? Or "originalX"? What about any other prefix?
prevFoo := somepkg.Foo
prevBar := somepkg.Bar
prevQuux := somepkg.Quux
prevGarply := somepkg.Garply
prevCorge := somepkg.Corge
defer func() {
	somepkg.Foo = prevFoo
	somepkg.Bar = prevBar
	somepkg.Quux = prevQuux
	somepkg.Garply = prevGarply
	somepkg.Corge = prevCorge
}()
```

or

```golang
prevFoo, prevBar, prevQuux := somepkg.Foo, somepkg.Bar, somepkg.Quux
prevGarply, prevCorge := somepkg.Garply, somepkg.Corge
defer func() {
	somepkg.Foo, somepkg.Bar, somepkg.Quux = prevFoo, prevBar
	somepkg.Garply, somepkg.Corge = prevQuux, prevGarply, prevCorge
}()
```

or any other variation you could come up with, I would always have

```golang
defer func(v Footype) { somepkg.Foo = v }(somepkg.Foo)
defer func(v Bartype) { somepkg.Bar = v }(somepkg.Bar)
defer func(v Quuxtype) { somepkg.Quux = v }(somepkg.Quux)
defer func(v Garplytype) { somepkg.Garply = v }(somepkg.Garply)
defer func(v Corgetype) { somepkg.Corge = v }(somepkg.Corge)
```

The fact that I chose `v` for the parameter name bears no significance from closure to closure, I could rename it in any or every one of them to any other valid symbol name, that's a detail that should not take up any brain cycles for you, me or anyone.

It also looks cleaner to me than any variation with multiple assignment.
</details>

Alright then, your final word, is this:

```diff
diff --git a/complete_test.go b/complete_test.go
index 9870910..3454926 100644
--- a/complete_test.go
+++ b/complete_test.go
@@ -226,8 +226,8 @@ func TestComplete(t *testing.T) {
 // ExampleComplete_outputCapturing demonstrates the ability to capture
 // the output of Complete() invocations, crucial for integration tests.
 func ExampleComplete_outputCapturing() {
-	defer func(f func(int)) { exit = f }(exit)
-	defer func(f getEnvFn) { getEnv = f }(getEnv)
+	prevExit, prevGetEnv := exit, getEnv
+	defer func() { exit, getEnv = prevExit, prevGetEnv }()
 	exit = func(int) {}
 
 	// This is where the actual example starts:
```

how you want it?

File: complete_test.go (hunk 2 above)
Comment (antichris) [reply complete_test.go]: I'm glad I could contribute an improvement.

Could you also, please, mark as such the conversations that you feel are resolved?

**Review by posener — APPROVED** [review]
