### PR TITLE
gocomplete: suppress error output by default

### LINKED ISSUE #139: gocomplete: stderr output jumbles up the prompt
## Repro

1. Follow the `gocomplete` installation procedure as detailed in the documentation.
2. Type `go test /bi` and press <kbd>Tab</kbd> once to trigger shell autocompletion.

### What is expected to happen

The line is completed as `go test /bin/ `. There is no additional output.

### What actually happens

The prompt is filled with diagnostic messages. On my system it looks like this:

```text
$ go test /bi2021/04/06 12:56:04 failed importing directory /bin: no buildable Go source files in /bin
2021/04/06 12:56:04 failed importing directory /boot: no buildable Go source files in /boot
2021/04/06 12:56:04 failed importing directory /cdrom: no buildable Go source files in /cdrom
2021/04/06 12:56:04 failed importing directory /dev: no buildable Go source files in /dev
2021/04/06 12:56:04 failed importing directory /etc: no buildable Go source files in /etc
2021/04/06 12:56:04 failed importing directory /home: no buildable Go source files in /home
2021/04/06 12:56:04 failed importing directory /lib: no buildable Go source files in /lib
2021/04/06 12:56:04 failed importing directory /lib32: no buildable Go source files in /lib32
2021/04/06 12:56:04 failed importing directory /lib64: no buildable Go source files in /lib64
2021/04/06 12:56:04 failed importing directory /lost+found: open /lost+found: permission denied
2021/04/06 12:56:04 failed importing directory /media: no buildable Go source files in /media
2021/04/06 12:56:04 failed importing directory /mnt: no buildable Go source files in /mnt
2021/04/06 12:56:04 failed importing directory /opt: no buildable Go source files in /opt
2021/04/06 12:56:04 failed importing directory /proc: no buildable Go source files in /proc
2021/04/06 12:56:04 failed importing directory /root: open /root: permission denied
2021/04/06 12:56:04 failed importing directory /run: no buildable Go source files in /run
2021/04/06 12:56:04 failed importing directory /sbin: no buildable Go source files in /sbin
2021/04/06 12:56:04 failed importing directory /snap: no buildable Go source files in /snap
2021/04/06 12:56:04 failed importing directory /srv: no buildable Go source files in /srv
2021/04/06 12:56:04 failed importing directory /sys: no buildable Go source files in /sys
2021/04/06 12:56:04 failed importing directory /tmp: no buildable Go source files in /tmp
2021/04/06 12:56:04 failed importing directory /usr: no buildable Go source files in /usr
2021/04/06 12:56:04 failed importing directory /var: no buildable Go source files in /var
2021/04/06 12:56:04 failed importing directory /: no buildable Go source files in /
n/ 
```

It's not that difficult to find your bearings and work from the assumption that the command was completed as expected (as described earlier) in this trivial case, but it becomes particularly annoying when you are in the middle of a more complex invocation, such as a build or a tool command with multiple flags, options and other parameters.

## Cause

A false assumption is made that all errors are always relevant to the end user and therefore everything should be dumped to `stderr` without distinction.

### PR DESCRIPTION
**Pull request by antichris**
Prevent the Go command completion from jumbling up the shell prompt on errors by setting the `Writer` of the Go standard library default `log.Logger` to `ioutil.Discard` unless the system environment variable `GOCOMP_VERBOSE` has been explicitly set to "1" (e.g. for debugging purposes).

Fixes #139

### CODE REVIEW

File: gocomplete/complete.go [hunk 1]
```diff
@@ -15,6 +22,10 @@ var (
 )
 
 func main() {
+	if os.Getenv(envVerbose) != "1" {
```
Comment (posener) [inline gocomplete/complete.go:25]: Maybe this could be a library feature and not specifically for gocomplete?
Can this change be in https://github.com/posener/complete/blob/v1/log.go?

**Review by posener — COMMENTED** [review]
Thanks!
See my comment.

File: gocomplete/complete.go (hunk 1 above)
Comment (antichris) [reply gocomplete/complete.go:25]: Yeah, I think it does make sense for something like it to be a part of the library. I'm really not sure about the exact design though. Was there any specific reason why the v1's `Log` was dropped from v2?

Comment (posener) [reply gocomplete/complete.go:25]: Oh, so sorry.
This `v1` default branch is confusing.
Yeh, I guess that the logs were removed because of the problem that you are facing.

**Review by posener — APPROVED** [review]
